CREATE TABLE [dbo].[Encounter] (
    [EncounterId]                          INT           IDENTITY (1, 1) NOT NULL,
    [RequestId]                            INT           NOT NULL,
    [MedicalHistory]                       VARCHAR (500) NULL,
    [Medications]                          VARCHAR (500) NULL,
    [Allergies]                            VARCHAR (500) NULL,
    [Temp]                                 VARCHAR (200) NULL,
    [HR]                                   VARCHAR (200) NULL,
    [RR]                                   VARCHAR (200) NULL,
    [Blood Pressure(S)]                    VARCHAR (100) NULL,
    [Blood Pressure(D)]                    VARCHAR (100) NULL,
    [O2]                                   VARCHAR (100) NULL,
    [Pain]                                 VARCHAR (100) NULL,
    [Heent]                                VARCHAR (200) NULL,
    [CV]                                   VARCHAR (200) NULL,
    [Chest]                                VARCHAR (200) NULL,
    [ABD]                                  VARCHAR (200) NULL,
    [Extr]                                 VARCHAR (200) NULL,
    [Skin]                                 VARCHAR (200) NULL,
    [Neuro]                                VARCHAR (200) NULL,
    [Other]                                VARCHAR (200) NULL,
    [Diagnosis]                            VARCHAR (200) NULL,
    [Treatment Plan]                       VARCHAR (200) NULL,
    [Medications Dispensed]                VARCHAR (200) NULL,
    [Procedures]                           VARCHAR (200) NULL,
    [Followup]                             VARCHAR (200) NULL,
    [location]                             VARCHAR (200) NULL,
    [History Of Present Illness Or Injury] VARCHAR (200) NULL,
    [IsFinalize]                           BIT           NULL,
    PRIMARY KEY CLUSTERED ([EncounterId] ASC),
    CONSTRAINT [Encounter_RequestId_fkey] FOREIGN KEY ([RequestId]) REFERENCES [dbo].[Request] ([RequestId])
);

