CREATE TABLE [dbo].[Physician] (
    [PhysicianId]        INT           IDENTITY (4, 1) NOT NULL,
    [FirstName]          VARCHAR (100) NOT NULL,
    [LastName]           VARCHAR (100) NULL,
    [Email]              VARCHAR (50)  NULL,
    [Mobile]             VARCHAR (20)  NULL,
    [MedicalLicense]     VARCHAR (500) NULL,
    [Photo]              VARCHAR (100) NULL,
    [AdminNotes]         VARCHAR (500) NULL,
    [Address1]           VARCHAR (500) NULL,
    [Address2]           VARCHAR (500) NULL,
    [City]               VARCHAR (100) NULL,
    [RegionId]           INT           NULL,
    [Zip]                VARCHAR (10)  NULL,
    [AltPhone]           VARCHAR (20)  NULL,
    [CreatedDate]        DATETIME      NOT NULL,
    [ModifiedDate]       DATETIME      NULL,
    [Status]             SMALLINT      NULL,
    [BusinessName]       VARCHAR (100) NOT NULL,
    [BusinessWebsite]    VARCHAR (200) NOT NULL,
    [RoleId]             INT           NULL,
    [NPINumber]          VARCHAR (500) NULL,
    [Signature]          VARCHAR (100) NULL,
    [IsTokenGenerate]    BIT           NULL,
    [SyncEmailAddress]   VARCHAR (50)  NULL,
    [AspNetUserId]       INT           NULL,
    [CreatedBy]          INT           NOT NULL,
    [ModifiedBy]         INT           NULL,
    [IsAgreementDoc]     BIT           NULL,
    [IsBackgroundDoc]    BIT           NULL,
    [IsTrainingDoc]      BIT           NULL,
    [IsNonDisclosureDoc] BIT           NULL,
    [IsDeleted]          BIT           NULL,
    [IsLicenseDoc]       BIT           NULL,
    [IsCredentialDoc]    BIT           NULL,
    PRIMARY KEY CLUSTERED ([PhysicianId] ASC),
    CONSTRAINT [Physician_AspNetUserId_fkey] FOREIGN KEY ([AspNetUserId]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [Physician_CreatedBy_fkey] FOREIGN KEY ([CreatedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [Physician_ModifiedBy_fkey] FOREIGN KEY ([ModifiedBy]) REFERENCES [dbo].[AspNetUsers] ([Id]),
    CONSTRAINT [Physician_RoleId_fkey] FOREIGN KEY ([RoleId]) REFERENCES [dbo].[Role] ([RoleId])
);

