CREATE TABLE [dbo].[RequestClient] (
    [RequestClientId]           INT           IDENTITY (1, 1) NOT NULL,
    [RequestId]                 INT           NULL,
    [FirstName]                 VARCHAR (100) NOT NULL,
    [LastName]                  VARCHAR (100) NULL,
    [PhoneNumber]               VARCHAR (23)  NULL,
    [Location]                  VARCHAR (100) NULL,
    [Address]                   VARCHAR (500) NULL,
    [RegionId]                  INT           NULL,
    [NotiMobile]                VARCHAR (20)  NULL,
    [NotiEmail]                 VARCHAR (50)  NULL,
    [Notes]                     VARCHAR (500) NULL,
    [Email]                     VARCHAR (50)  NULL,
    [strMonth]                  VARCHAR (20)  NULL,
    [intYear]                   INT           NULL,
    [intDate]                   INT           NULL,
    [IsMobile]                  BIT           NULL,
    [Street]                    VARCHAR (100) NULL,
    [City]                      VARCHAR (100) NULL,
    [State]                     VARCHAR (100) NULL,
    [ZipCode]                   VARCHAR (10)  NULL,
    [CommunicationType]         SMALLINT      NULL,
    [RemindReservationCount]    SMALLINT      NULL,
    [RemindHouseCallCount]      SMALLINT      NULL,
    [IsSetFollowupSent]         SMALLINT      NULL,
    [IP]                        VARCHAR (20)  NULL,
    [IsReservationReminderSent] SMALLINT      NULL,
    [Latitude]                  NUMERIC (9)   NULL,
    [Longitude]                 NUMERIC (9)   NULL,
    PRIMARY KEY CLUSTERED ([RequestClientId] ASC),
    CONSTRAINT [RequestClient_RegionId_fkey] FOREIGN KEY ([RegionId]) REFERENCES [dbo].[Region] ([RegionId]),
    CONSTRAINT [RequestClient_RequestId_fkey] FOREIGN KEY ([RequestId]) REFERENCES [dbo].[Request] ([RequestId])
);

