CREATE TABLE [dbo].[Request] (
    [RequestId]            INT           IDENTITY (1, 1) NOT NULL,
    [RequestTypeId]        INT           NOT NULL,
    [UserId]               INT           NULL,
    [FirstName]            VARCHAR (100) NULL,
    [LastName]             VARCHAR (100) NULL,
    [PhoneNumber]          VARCHAR (23)  NULL,
    [Email]                VARCHAR (50)  NULL,
    [Status]               SMALLINT      NOT NULL,
    [PhysicianId]          INT           NULL,
    [ConfirmationNumber]   VARCHAR (20)  NULL,
    [ModifiedDate]         DATETIME      NULL,
    [DeclinedBy]           VARCHAR (250) NULL,
    [IsUrgentEmailSent]    BIT           NULL,
    [LastWellnessDate]     DATETIME      NULL,
    [IsMobile]             BIT           NULL,
    [CallType]             SMALLINT      NULL,
    [CompletedByPhysician] BIT           NULL,
    [LastReservationDate]  DATETIME      NULL,
    [AcceptedDate]         DATETIME      NULL,
    [RelationName]         VARCHAR (100) NULL,
    [CaseNumber]           VARCHAR (50)  NULL,
    [IP]                   VARCHAR (20)  NULL,
    [CaseTag]              VARCHAR (50)  NULL,
    [CaseTagPhysician]     VARCHAR (50)  NULL,
    [PatientAccountId]     VARCHAR (128) NULL,
    [CreatedUserId]        INT           NULL,
    [CreatedDate]          DATETIME      NULL,
    [IsDeleted]            BIT           NULL,
    PRIMARY KEY CLUSTERED ([RequestId] ASC),
    CONSTRAINT [Request_PhysicianId_fkey] FOREIGN KEY ([PhysicianId]) REFERENCES [dbo].[Physician] ([PhysicianId])
);

